name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build core with Ant
      run: cd core && ant -f build.xml
    - name: Unit test core with Ant
      run: cd core && ant -f build.xml test
